<?php
  return[
    'LISENCE' => [
        1=>[
            'code'=>"BA",
            'text'=>"行動価値検査",
            'list'=>[
                1=>[
                    "code"=>"BA-J1",
                    "text"=>"行動価値検査1"
                ],
                2=>[
                    "code"=>"BA-J2",
                    "text"=>"行動価値検査2"
                ],
                3=>[
                    "code"=>"BA-J3",
                    "text"=>"行動価値検査3"
                ],
                4=>[
                    "code"=>"BA-J4",
                    "text"=>"行動価値検査4"
                ],
                5=>[
                    "code"=>"PFS",
                    "text"=>"PFS検査"
                ],
                6=>[
                    "code"=>"PFS2",
                    "text"=>"PFS検査2"
                ],
                7=>[
                    "code"=>"PFS3",
                    "text"=>"PFS検査3"
                ],
            ]
        ],
        2=>[
            'code'=>"EA",
            'text'=>"感情能力検査",
            'list'=>[
                1=>[
                    "code"=>"EA-S",
                    "text"=>"感情能力検査"
                ],
                2=>[
                    "code"=>"EA-BJ",
                    "text"=>"感情能力検査"
                ],
                3=>[
                    "code"=>"EA-S2",
                    "text"=>"感情能力検査"
                ],
                4=>[
                    "code"=>"感情能力検査Ib",
                    "text"=>"EA-Ib"
                ],
                5=>[
                    "code"=>"EA-BJ2",
                    "text"=>"感情能力検査"
                ],
                6=>[
                    "code"=>"感情能力検査Ia",
                    "text"=>"EA-Ia"
                ]
            ]
        ],
        3=>[
            'code'=>"FS",
            'text'=>"Welcome Fs検査",
            'list'=>[
                1=>[
                    "code"=>"Fs",
                    "text"=>"Welcome Fs検査"
                ]
            ]
        ],
        4=>[
            'code'=>"VF",
            'text'=>"VF検査",
            'list'=>[
                1=>[
                    "code"=>"VF-J",
                    "text"=>"VF検査"
                ],
                2=>[
                    "code"=>"VF-J2",
                    "text"=>"VF検査"
                ]
            ]
        ],
        5=>[
            'code'=>"SA",
            'text'=>"行動意識検査",
            'list'=>[
                1=>[
                    "code"=>"SA-J",
                    "text"=>"行動意識検査"
                ],
                2=>[
                    "code"=>"SA-J2",
                    "text"=>"行動意識検査"
                ]
            ]
        ],
        6=>[
            'code'=>"TH",
            'text'=>"多面評価検査",
            'list'=>[
                1=>[
                    "code"=>"TH",
                    "text"=>"多面評価検査"
                ],
            ]
        ],
        7=>[
            'code'=>"IQ",
            'text'=>"知的能力検査",
            'list'=>[
                1=>[
                    "code"=>"IQ",
                    "text"=>"知的能力検査"
                ],
            ]
        ],
        8=>[
            'code'=>"BMS",
            'text'=>"数学検定検査",
            'list'=>[
                1=>[
                    "code"=>"BMS",
                    "text"=>"数学検定検査"
                ],
                2=>[
                    "code"=>"BMS2",
                    "text"=>"数学検定検査"
                ],
                3=>[
                    "code"=>"BMS3",
                    "text"=>"数学検定検査"
                ],
            ]
        ],
        9=>[
            'code'=>"OCS",
            'text'=>"職場研究",
            'list'=>[
                1=>[
                    "code"=>"OCS",
                    "text"=>"職場研究"
                ],
            ]
        ],
        10=>[
            'code'=>"nl",
            'text'=>"NL検査",
            'list'=>[
                1=>[
                    "code"=>"NL-J",
                    "text"=>"NL検査"
                ],
                2=>[
                    "code"=>"NL-J2",
                    "text"=>"NL検査"
                ],
                3=>[
                    "code"=>"NL-J3",
                    "text"=>"NL検査"
                ],
            ]
        ],
        11=>[
            'code'=>"pa",
            'text'=>"親用検査",
            'list'=>[
                1=>[
                    "code"=>"PA-J",
                    "text"=>"親用検査"
                ],
            ]
        ]
     ]
  ];
