<?php
  return[
    'LISENCE' => [
        1=>[
            'code'=>"BA",
            'text'=>"行動価値検査",
            'list'=>[
                1=>[
                    "code"=>"BA-J1",
                    "text"=>"行動価値検査1"
                ]
            ]
        ],
        2=>[
            'code'=>"EA",
            'text'=>"感情能力検査",
            'list'=>[
                1=>[
                    "code"=>"EA-S",
                    "text"=>"感情能力検査"
                ]
            ]
        ]
     ]
  ];
